spring.datasource.url=jdbc:postgresql://localhost:5432/hmsdb
spring.datasource.username=postgres
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.thymeleaf.cache=false
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

java.net.preferIPv4Stack=true
java.net.preferIPv6Addresses=false

server.port=8080

# Gemini (use env variable)
groq.api.key=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
